#!/bin/bash
filename="entrypoint"

set -o errexit
set -o pipefail
set -o nounset

if  [ -z "${POSTGRES_USER}" ]; then
  base_postgres_image_default_user='postgres'
  export POSTGRES_USER="${base_postgres_image_default_user}"
fi

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

echo "${filename}:DATABASE_URL:${DATABASE_URL}"

# python /test_db.py

# We can't move this to a python file as we need environment variables
python << END
import sys
import time
import psycopg2

suggest_unrecoverable_after = 30
start = time.time()

print("Connecting to postgres on {}".format("${POSTGRES_DB}"))
while True:
  try:
    psycopg2.connect(
      dbname="${POSTGRES_DB}",
      user="${POSTGRES_USER}",
      password="${POSTGRES_PASSWORD}",
      host="${POSTGRES_HOST}",
      port="${POSTGRES_PORT}",
    )
    print("Connection Successful!")
    break
  except psycopg2.OperationalError as error:
    sys.stderr.write("Waiting for PostgreSQL on {} to become available...\n".format("${POSTGRES_HOST}"))
    if time.time() - start > suggest_unrecoverable_after:
      sys.stderr.write(" This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))
    time.sleep(1)
END

exec "$@"